import React, { useState, useEffect } from 'react';
import { Button } from './ui/Button';
import { Spinner } from './ui/Spinner';
import { audioPlayer } from '../services/audioService';
import { generateSpeechFromText } from '../services/geminiService';

interface StoryDisplayProps {
  storyText: string;
  isStoryLoading: boolean;
}

export const StoryDisplay: React.FC<StoryDisplayProps> = ({ storyText, isStoryLoading }) => {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isAudioLoading, setIsAudioLoading] = useState(false);
  const [audioData, setAudioData] = useState<string | null>(null);

  useEffect(() => {
    // Reset audio state when story changes
    setAudioData(null);
    setIsSpeaking(false);
    audioPlayer.stop();
  }, [storyText]);

  const handleReadAloud = async () => {
    if (isSpeaking) {
      audioPlayer.stop();
      setIsSpeaking(false);
      return;
    }

    setIsSpeaking(true);

    try {
      // If we already have the audio data, just play it
      if (audioData) {
        await audioPlayer.playPCM(audioData, () => setIsSpeaking(false));
        return;
      }

      // Otherwise, generate it first
      setIsAudioLoading(true);
      const generatedAudio = await generateSpeechFromText(storyText);
      setAudioData(generatedAudio);
      setIsAudioLoading(false);
      
      await audioPlayer.playPCM(generatedAudio, () => setIsSpeaking(false));

    } catch (error) {
      console.error(error);
      setIsSpeaking(false);
      setIsAudioLoading(false);
      alert("Failed to generate or play speech.");
    }
  };

  if (isStoryLoading) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-12 space-y-4 text-center animate-pulse">
        <div className="h-4 bg-slate-700 rounded w-3/4"></div>
        <div className="h-4 bg-slate-700 rounded w-full"></div>
        <div className="h-4 bg-slate-700 rounded w-5/6"></div>
        <div className="h-4 bg-slate-700 rounded w-2/3"></div>
        <p className="text-slate-400 mt-8 font-medium">Dreaming up a world...</p>
      </div>
    );
  }

  if (!storyText) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-8 text-slate-500 border-2 border-dashed border-slate-700 rounded-2xl bg-slate-800/30">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 mb-4 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
        </svg>
        <p className="text-lg font-medium">Waiting for inspiration...</p>
        <p className="text-sm mt-2">Upload an image to start writing.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      <div className="flex-grow overflow-y-auto pr-2">
        <div className="prose prose-invert prose-lg max-w-none">
          <p className="font-serif leading-loose text-slate-200 text-lg md:text-xl first-letter:text-5xl first-letter:font-bold first-letter:text-primary first-letter:mr-3 first-letter:float-left">
            {storyText}
          </p>
        </div>
      </div>
      
      <div className="mt-8 pt-6 border-t border-slate-700 flex flex-col sm:flex-row justify-between items-center gap-4">
         <div className="text-sm text-slate-400 italic">
            Generated by Gemini 3 Pro
         </div>
         <Button 
           onClick={handleReadAloud}
           variant={isSpeaking ? 'danger' : 'secondary'}
           isLoading={isAudioLoading}
           className="w-full sm:w-auto min-w-[160px]"
           icon={
             isSpeaking ? (
               <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                 <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z" clipRule="evenodd" />
               </svg>
             ) : (
               <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                 <path fillRule="evenodd" d="M9.383 3.076A1 1 0 0110 4v12a1 1 0 01-1.707.707L4.586 13H2a1 1 0 01-1-1V8a1 1 0 011-1h2.586l3.707-3.707a1 1 0 011.09-.217zM14.657 2.929a1 1 0 011.414 0A9.972 9.972 0 0119 10a9.972 9.972 0 01-2.929 7.071 1 1 0 01-1.414-1.414A7.971 7.971 0 0017 10c0-2.21-.894-4.208-2.343-5.657a1 1 0 010-1.414zm-2.829 2.828a1 1 0 011.415 0A5.983 5.983 0 0115 10a5.984 5.984 0 01-1.757 4.243 1 1 0 01-1.415-1.415A3.984 3.984 0 0013 10a3.983 3.983 0 00-1.172-2.828 1 1 0 010-1.414z" clipRule="evenodd" />
               </svg>
             )
           }
         >
           {isSpeaking ? 'Stop Narration' : 'Read Aloud'}
         </Button>
      </div>
    </div>
  );
};